Add Maven support and tests
Maven support added because couldn't make IntelliJ run JUnit5 tests
without it. Despite the fact that it should be possible I ran into
the same error over and over:
"NoClassDefFoundError: org/junit/platform/commons/util/Preconditions"
Instead of fighting it too hard the project has been mavenized and
it worked beautifully.
Tests for the key method replaceAll() added.